services:
  fluentd:
    build:
        context: ./fluentd
        dockerfile: Dockerfile.fluentd
    ports:
      - "9884:9884"
    volumes:
      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf
    depends_on:
      - kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  init-kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    entrypoint: [ '/bin/bash', '-c' ]
    command: |
      "
      # blocks until kafka is reachable
      kafka-topics --bootstrap-server PLAINTEXT://kafka:9092 --list

      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server PLAINTEXT://kafka:9092 --create --if-not-exists --topic locations --replication-factor 1 --partitions 1

      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server PLAINTEXT://kafka:9092 --list
      "
  redis-host:
    image: redis:latest
    ports:
      - "6379:6379"

  spark:
    build: 
      context : ./spark
      dockerfile: Dockerfile.spark
    depends_on:
      - kafka
      - redis-host
    environment:
      - SPARK_MASTER_NAME=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
      - SPARK_DRIVER_MEMORY=2g
    ports:
      - "4040:4040"
      - "8082:8082"